[project]
name = "postillon-newstickers-scraper"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
    "typing-extensions (>=4.15.0,<5.0.0)",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
